services:
  - type: web
    name: task-manager-backend
    runtime: python
    plan: free
    buildCommand: |
      apt-get update
      apt-get install -y curl apt-transport-https gnupg unixodbc unixodbc-dev
      curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
      curl https://packages.microsoft.com/config/debian/11/prod.list > /etc/apt/sources.list.d/mssql-release.list
      apt-get update
      ACCEPT_EULA=Y apt-get install -y msodbcsql18
      pip install -r requirements.txt
    startCommand: gunicorn backend.wsgi:application
